### ISSUE TITLE
Online services

### ISSUE THREAD

**Issue by dude2093350** [D-Multi-cTech/Racing-World#3]
Should we include online multiplayer, it may cost a little bit but it could make the game more fun, if so i'll work on that, also who is the publisher, we are both developers but who will publish, I could if you want but you can if you would like.

**Comment by dude2093350** [comment]
Publisher=seller

**Comment by dguis** [comment]
Hmm. I don't know. You could I guess. Please visit https://github.com/D-Multi-cTech/Racing-World/invitations to receive admin access to this repo.

**Comment by dguis** [comment]
I think we should have online multiplayer. By the way, how did you learn how to use Unity?

**Comment by dude2093350** [comment]
Bought some stuff, mostly taught myself

**Comment by dude2093350** [comment]
Okay, i'll publish and work on marketing, i'll put in online multiplayer access
