### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by dude2093350** [D-Multi-cTech/Racing-World#5]
Since it appears I'm the publisher, I would like to work on marketing, is this okay?

**Comment by dguis** [comment]
Yes. Just wondering, what format is that logo in the project menu in unity?

**Comment by dude2093350** [comment]
.jpeg, then I convert it to a sprite

**Comment by dguis** [comment]
How do you do that?

**Comment by dguis** [comment]
(Sorry. I want to figure out how to use Unity better)

**Comment by dude2093350** [comment]
Just give me an image, it is under the 'player' tab above the hierarchy

**Comment by dguis** [comment]
![splash](https://user-images.githubusercontent.com/20483504/41103759-c2d7e468-6a1e-11e8-9435-8131cf354977.jpg)

**Comment by dude2093350** [comment]
oh, and how do you get that old version of... photoshop?

**Comment by dude2093350** [comment]
I need it in file format under `<code>` section!

**Comment by dude2093350** [comment]
.jpeg

**Comment by dude2093350** [comment]
sorry .jpg

**Comment by dguis** [comment]
I believe it is here: https://helpx.adobe.com/creative-suite/kb/cs2-product-downloads.html?promoid=19SCDRQK

**Comment by dguis** [comment]
Uploaded

**Comment by dude2093350** [comment]
"Adobe no longer allows downloads or licenses of this product"

**Comment by dude2093350** [comment]
WAIT appy it to the .Splash prefab then under build sttings re-align in the image, don't full screen.

**Comment by dude2093350** [comment]
Okay, thanks

**Comment by dude2093350** [comment]
Over to xbox chat

**Comment by dguis** [comment]
You should do this. Unity started updating.

**Comment by dude2093350** [comment]
?
